package graph_solver;

option java_multiple_files = true;
option java_package = "projects.multipath.protos";
option java_outer_classname = "GraphSolverProtos";

message Instance {
  repeated Node nodes = 1;
  repeated Assignment assignments = 2;
}

message Assignment {
  required int32 robot_id = 1;
  required int32 start_id = 2;
  required int32 finish_id = 3;
}

message Node {
  required int32 id = 1;
  repeated int32 neighbors = 2;
}

message Solution {
  required int32 status = 1;
  repeated Timestep timesteps = 2;
}

message Timestep {
  required int32 time = 1;
  repeated Position positions = 2;
}

message Position {
  required int32 robot_id = 1;
  required int32 node_id = 2;
}
